name: aibs
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.5.2
    - numpy
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.9.4
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - h5py
    - matplotlib
    - opencv3=3.2.0
    - scikit-learn
    - tensorflow
    - pip:
        - Pillow
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - msgpack-python
        - cached_property
        - Cython
        - awscli
        - pyglet
        - gym[all]
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
